[project]
name = "uprate"
version = "0.3"
description = "Ratelimits. Dumbified. A fully typed, simple ratelimit library."
authors = [{ name = "WizzyGeek", email = "ojasscoding@gmail.com" }]
requires-python = ">=3.9,<4"
readme = "README.md"
license = "MIT"
keywords = [
    "ratelimits",
    "limits",
    "ratelimit",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.optional-dependencies]
docs = [
    "Sphinx>=4.1.1,<5",
    "myst-parser>=0.15.1,<0.16",
    "furo>=2021.7.5b38,<2022",
    "sphinx-copybutton>=0.4.0,<0.5",
]

[project.urls]
Homepage = "https://github.com/WizzyGeek/uprate#readme"
Repository = "https://github.com/WizzyGeek/uprate"
Documentation = "https://uprate.readthedocs.io/en/latest/"
"Bug Tracker" = "https://github.com/WizzyGeek/uprate/issues"
Discord = "https://discord.gg/udmdsFk6Yx"

[dependency-groups]
dev = ["mypy>=0.910,<0.911"]

[tool.uv]

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.mypy]
show_error_codes = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
files = ["uprate", "tests"]
exclude = "docs/"
python_version = "3.10"

[tool.pyright]
include = ["uprate"]
exclude = ["docs", ".git", "**/__pycache__", ".mypy_cache"]
ignore = [".venv"]
