[project]
name = "uprate"
version = "0.3"
description = "Ratelimits. Dumbified. A fully typed, simple ratelimit library."
authors = [{ name = "WizzyGeek", email = "ojasscoding@gmail.com" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = "MIT"
keywords = [
    "ratelimits",
    "limits",
    "ratelimit",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.optional-dependencies]


[project.urls]
Homepage = "https://github.com/WizzyGeek/uprate#readme"
Repository = "https://github.com/WizzyGeek/uprate"
Documentation = "https://uprate.readthedocs.io/en/latest/"
"Bug Tracker" = "https://github.com/WizzyGeek/uprate/issues"
Discord = "https://discord.gg/udmdsFk6Yx"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
]
docs = [
    "furo>=2025.12.19",
    "myst-parser>=5.1.0",
    "sphinx>=9",
    "sphinx-copybutton>=0.5.2",
]

[tool.uv]

[tool.uv.dependency-groups]
# Tell uv that this specific group targets Python 3.11+
docs = { requires-python = ">=3.11" }
dev = { requires-python = ">=3.10" }

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.mypy]
show_error_codes = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
files = ["uprate"]
exclude = "docs/"
python_version = "3.10"

[tool.pyright]
include = ["uprate"]
exclude = ["docs", ".git", "**/__pycache__", ".mypy_cache", "**/node_modules", "**/.*", ".venv"]
ignore = [".venv"]
